---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fred
spec:
  interval: 5m
  chart:
    spec:
      # Source:
      chart: charts/fred
      version: 0.1.0
      sourceRef:
        kind: GitRepository
        name: flux-config
        namespace: flux-system
  values:
    image:
      tag: fred-cap
      # Available tags:
      # fred
      # frida
      # fred-xmas
      # fred-pirate
      # fred-cap
      # fred-easter

      # flux reconcile source git flux-config -n flux-system
      # k get kustomization -A
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: k8s.mbrandl.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: k8s.mbrandl.com
          hosts:
            - k8s.mbrandl.com
