---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fred
spec:
  values:
    image:
      tag: fred-easter
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: k8s.mbrandl.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: k8s.mbrandl.com
          hosts:
            - k8s.mbrandl.com
